name: Photopia
favicon: null
layout_spectrum: 0.8026201128959656
typography_spectrum: 0.37292857049033046
title: 'Photopia Studio - Commercial and portrait photography - Studio hire - In Gladstone, QLD'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#eceae6'
    - '#e75d2c'
    - '#a3a3a2'
    - '#504949'
    - '#000000'
  brandStrength: 0.6787426332011819
  lightness: 0.7465896029025316
  saturation: 0.48270639358088374
  rhythmicContrast: 0.5219117267988622
purpose: []
